# Generated by Django 4.0.1 on 2022-01-18 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer1', models.CharField(blank=True, max_length=100, null=True)),
                ('offer2', models.CharField(blank=True, max_length=100, null=True)),
                ('offer3', models.CharField(blank=True, max_length=100, null=True)),
                ('offer4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1', models.CharField(blank=True, max_length=200, null=True)),
                ('feature2', models.CharField(blank=True, max_length=200, null=True)),
                ('feature3', models.CharField(blank=True, max_length=200, null=True)),
                ('feature4', models.CharField(blank=True, max_length=200, null=True)),
                ('specification', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand'),
        ),
        migrations.AddField(
            model_name='products',
            name='available_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.availableoffer'),
        ),
        migrations.AlterField(
            model_name='products',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.feature'),
        ),
    ]
