# Generated by Django 4.0.1 on 2022-01-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_availableoffer_feature_category_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='color',
            field=models.CharField(blank=True, choices=[('RED', 'red'), ('WHITE', 'white'), ('SKY_BLUE', 'sky_blue'), ('BLACK', 'black'), ('SILVER', 'SILVER'), ('GREEN', 'green')], max_length=50, null=True),
        ),
    ]
