# Generated by Django 4.0.1 on 2022-01-19 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_brand_feature_brand_delete_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='product',
        ),
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
