# Generated by Django 4.0.1 on 2022-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_subcategory_product_products_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_name',
            field=models.CharField(max_length=100),
        ),
    ]
