# Generated by Django 4.0.1 on 2022-01-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_cart_added_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='color',
            field=models.CharField(blank=True, choices=[('RED', 'red'), ('WHITE', 'white'), ('SKY_BLUE', 'sky_blue'), ('BLACK', 'black'), ('SILVER', 'SILVER'), ('GREEN', 'green'), ('GOLDEN', 'golden'), ('BRONZE', 'bronze'), ('YELLOW', 'Yellow'), ('PURPLE', 'Purple'), ('PINK', 'Pink')], max_length=50, null=True),
        ),
    ]
