# Generated by Django 4.0.1 on 2022-01-11 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(9999999)]),
        ),
    ]
