# Generated by Django 4.0.1 on 2022-01-17 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_address_country_address_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
