# Generated by Django 4.0.1 on 2022-01-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/user_profile/default_image/default-user-photo-79.jpg', null=True, upload_to='user_profile'),
        ),
    ]
